kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-orchestrator-jobs-manager
subjects:
  - kind: ServiceAccount
    name: job-orchestrator
    namespace: rhn-gps-aclark-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jobs-manager
